location                     = "Central US"
local_ip_address             = "YOUR PUBLIC IP ADDRESS"
local_address_space          = "192.168.1.0/24"
preshared_key                = "foo"
log_analytics_workspace_name = "log-foo"
observability_resource_group = "rg-observability-foo"
admin_user_id                = "YOUR AZURE AD USER ID"